In [10]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%precision 3

'%.3f'

In [66]:
data = np.array([5,6,4,7,9,2,3,8,9])
print('型: ', data.dtype)
print('次元数: ', data.ndim)
print('総素数: ', data.size)
print('元データ:', data)
print('それぞれの要素に掛け算: ', data * 2)
print('配列×配列: ', data + np.array([2,2,2,2,2,2,2,2,2]))
data.sort()
print('ソート: ', data)
print('最大: ', data.max())
print('積み上げ: ', data.cumsum())
random.seed(0)
print('正規分布、平均０、標準偏差1: ', random.randn(10))
print('重複ありの取り出し（復元抽出): ', random.choice(data, 5))
print('重複なしの取り出し(非復元抽出): ', random.choice(data, 5, replace = False))

型:  int64
次元数:  1
総素数:  9
元データ: [5 6 4 7 9 2 3 8 9]
それぞれの要素に掛け算:  [10 12  8 14 18  4  6 16 18]
配列×配列:  [ 7  8  6  9 11  4  5 10 11]
ソート:  [2 3 4 5 6 7 8 9 9]
最大:  9
積み上げ:  [ 2  5  9 14 20 27 35 44 53]
正規分布、平均０、標準偏差1:  [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]
重複ありの取り出し（復元抽出):  [8 9 9 9 3]
重複なしの取り出し(非復元抽出):  [4 6 5 8 9]


In [98]:
data1 = np.arange(9).reshape(3, 3)
print('行列data1: \n', data1)
print('行列の一列目: ', data1[0, :])
print('行列の一行目: ', data1[:, 0])
data2 = np.arange(9, 18).reshape(3, 3)
print('行列data2: \n', data2)
print('行列の掛け算: \n', np.dot(data1, data2))
print('全部0の行列、int64の型指定: \n', np.zeros((2, 3), dtype = np.int64))
print('全部1の行列、float64の型指定: \n', np.ones((2, 3), dtype = np.float64))

行列data1: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
行列の一列目:  [0 1 2]
行列の一行目:  [0 3 6]
行列data2: 
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
行列の掛け算: 
 [[ 42  45  48]
 [150 162 174]
 [258 279 300]]
全部0の行列、int64の型指定: 
 [[0 0 0]
 [0 0 0]]
全部1の行列、float64の型指定: 
 [[1. 1. 1.]
 [1. 1. 1.]]
